//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 
namespace MyApplication {
    using System.Xml.Serialization;
      
    public partial class MyApplication {
        
        private string applicationDateField;
        
        private string createdOnField;
        
        private string modifiedOnField;
        
        private string companyField;
        
        private string titleField;
        
        private string advertisementField;
        
        private string urlField;
        
        private string advertiserField;
        
        private string appliedCVBinaryField;
        
        /// <remarks/>
        public string ApplicationDate {
            get {
                return this.applicationDateField;
            }
            set {
                this.applicationDateField = value;
            }
        }
        
        /// <remarks/>
        public string CreatedOn {
            get {
                return this.createdOnField;
            }
            set {
                this.createdOnField = value;
            }
        }
        
        /// <remarks/>
        public string ModifiedOn {
            get {
                return this.modifiedOnField;
            }
            set {
                this.modifiedOnField = value;
            }
        }
        
        /// <remarks/>
        public string Company {
            get {
                return this.companyField;
            }
            set {
                this.companyField = value;
            }
        }
        
        /// <remarks/>
        public string Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
        
        /// <remarks/>
        public string Advertisement {
            get {
                return this.advertisementField;
            }
            set {
                this.advertisementField = value;
            }
        }
        
        /// <remarks/>
        public string Url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
            }
        }
        
        /// <remarks/>
        public string Advertiser {
            get {
                return this.advertiserField;
            }
            set {
                this.advertiserField = value;
            }
        }
        
        /// <remarks/>
        public string AppliedCVBinary {
            get {
                return this.appliedCVBinaryField;
            }
            set {
                this.appliedCVBinaryField = value;
            }
        }
    }
}
